services:
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports: [3306:3306]
  
  adminer:
    image: adminer:4.8.1
    ports: [8080:8080]